@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 14 13:11:56 -0700 2024
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim RISC_CPUPipeline_Testbench_behav -key {Behavioral:sim_1:Functional:RISC_CPUPipeline_Testbench} -tclbatch RISC_CPUPipeline_Testbench.tcl -view C:/Users/Aworinde David/Documents/NEW1/wetransfer_wetransfer_hw5_2024-04-02_1856_2024-04-02_2158/wetransfer_hw5_2024-04-02_1856/HW5/RISC_CPUPipeline_Testbench_behav1.wcfg -log simulate.log"
call xsim  RISC_CPUPipeline_Testbench_behav -key {Behavioral:sim_1:Functional:RISC_CPUPipeline_Testbench} -tclbatch RISC_CPUPipeline_Testbench.tcl -view C:/Users/Aworinde David/Documents/NEW1/wetransfer_wetransfer_hw5_2024-04-02_1856_2024-04-02_2158/wetransfer_hw5_2024-04-02_1856/HW5/RISC_CPUPipeline_Testbench_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
