"""
ML Model Backtest
=================
Loads the trained meta-model and runs a bar-by-bar backtest on historical data.

Shows P&L, accuracy, Sharpe, win rate, profit factor, and drawdown for each symbol
using ONLY signals generated by the trained XGBoost meta-model.

Run inside the backend container:
    python backtest_ml.py
    python backtest_ml.py --days 252 --threshold 0.55
    python backtest_ml.py --symbol AAPL --days 365

Note: data is fetched directly from yfinance — no DB required.
"""
from __future__ import annotations

import argparse
import asyncio
import math
import sys
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_DIR = Path(__file__).parent / "models"

WATCHLIST = [
    "AAPL", "TSLA", "MSFT", "NVDA", "AMZN",
    "GOOGL", "META", "SPY", "BTC-USD", "ETH-USD", "SOL-USD",
]

N_FORWARD      = 5       # bars ahead for trade exit
SLIPPAGE_BPS   = 5.0     # basis points per side
COMMISSION_PCT = 0.001   # 0.1% per side


# ── Data loading ──────────────────────────────────────────────────────────────

def _fetch_yf(symbol: str, start: date, end: date) -> pd.DataFrame | None:
    try:
        df = yf.download(
            symbol, start=str(start),
            end=str(end + timedelta(days=1)),
            interval="1d", auto_adjust=True,
            progress=False, multi_level_index=False,
        )
    except Exception as exc:
        print(f"  yfinance {symbol}: {exc}")
        return None

    if df is None or df.empty:
        return None
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df.columns = [c.lower() for c in df.columns]
    req = {"open", "high", "low", "close", "volume"}
    if not req.issubset(set(df.columns)):
        return None
    return df[list(req)].dropna()


# ── Model loading ─────────────────────────────────────────────────────────────

def load_models():
    """Load all three trained model files using their class .load() methods."""
    for fname in ("meta_model.pkl", "regime_detector.pkl", "calibration.pkl"):
        if not (MODEL_DIR / fname).exists():
            print(f"ERROR: model file not found: {MODEL_DIR / fname}")
            print("Run the ML training first: POST /tasks/train-models")
            sys.exit(1)

    sys.path.insert(0, str(Path(__file__).parent))

    from app.ml.meta_model import MetaModel
    from app.analysis.regime.detector import RegimeDetector
    from app.ml.calibration import CalibrationEngine

    meta_model  = MetaModel.load(MODEL_DIR / "meta_model.pkl")
    regime_det  = RegimeDetector.load(MODEL_DIR / "regime_detector.pkl")
    calibration = CalibrationEngine.load(MODEL_DIR / "calibration.pkl")

    return meta_model, regime_det, calibration


# ── Feature pipeline ──────────────────────────────────────────────────────────

def build_features_for_symbol(df: pd.DataFrame, symbol: str,
                               regime_det, meta_model, calib) -> list[dict]:
    """
    For every bar in df, compute the full feature vector and run the ML models.
    Returns list of {date, signal, confidence, direction_probs, close, entry_price}.
    """
    from app.analysis.features.pipeline import FeaturePipeline
    from app.ml.meta_model import build_feature_vector

    pipe = FeaturePipeline(min_bars=50)
    try:
        fsets = pipe.compute(df, symbol=symbol, mode="batch")
    except Exception as exc:
        print(f"  FeaturePipeline error {symbol}: {exc}")
        return []

    if not fsets:
        return []

    # Fit regime detector on all features from this symbol
    all_feat_dicts = [fs.to_dict() for fs in fsets]
    try:
        if not regime_det._fitted:
            regime_det.fit(all_feat_dicts)
    except Exception:
        pass  # use rule-based fallback

    bars = []
    for i, fs in enumerate(fsets):
        try:
            regime_result = regime_det.predict(fs.to_dict())
            fv = build_feature_vector(
                fs.to_dict(), regime_result,
                strategy_signals={},
                sentiment={"score": 0.0, "confidence": 0.0},
            )
            result = meta_model.predict(fv)

            raw_conf = result["raw_confidence"]
            cal_conf = float(calib.calibrate(raw_conf)) if calib._fitted else raw_conf

            bars.append({
                "date":           df.index[i],
                "close":          float(df["close"].iloc[i]),
                "open_next":      float(df["open"].iloc[i + 1]) if i + 1 < len(df) else float(df["close"].iloc[i]),
                "signal":         result["signal"],
                "raw_conf":       raw_conf,
                "cal_conf":       cal_conf,
                "exp_return":     result["expected_return"],
                "exp_drawdown":   result["expected_drawdown"],
                "direction_probs": result["direction_probs"],
            })
        except Exception as exc:
            continue

    return bars


# ── Trade simulation ──────────────────────────────────────────────────────────

def simulate_trades(bars: list[dict], threshold: float, initial_capital: float = 100_000.0) -> dict:
    """
    Bar-by-bar simulation.
    Entry at next bar's open after signal. Exit after N_FORWARD bars or on opposing signal.
    """
    n = len(bars)
    equity = initial_capital
    position = None   # {"entry_price", "direction", "entry_bar", "size"}
    trades   = []
    equity_curve = [{"date": bars[0]["date"], "equity": equity}] if bars else []

    for i, bar in enumerate(bars):
        # Check if we should exit an open position
        if position is not None:
            bars_held = i - position["entry_bar"]
            should_exit = (
                bars_held >= N_FORWARD or
                (bar["signal"] != "HOLD" and bar["cal_conf"] >= threshold and
                 bar["signal"] != position["direction"])
            )

            if should_exit:
                exit_price = bar["open_next"] if i + 1 < n else bar["close"]
                direction  = position["direction"]
                entry_price = position["entry_price"]
                size = position["size"]

                raw_pnl = (exit_price - entry_price) / entry_price
                if direction == "SELL":
                    raw_pnl = -raw_pnl

                slip_cost = SLIPPAGE_BPS / 10_000 * 2   # entry + exit
                comm_cost = COMMISSION_PCT * 2
                net_pnl_pct = raw_pnl - slip_cost - comm_cost

                pnl_dollar = size * net_pnl_pct
                equity    += pnl_dollar

                trades.append({
                    "entry_date":  position["entry_date"],
                    "exit_date":   bar["date"],
                    "symbol":      position.get("symbol", ""),
                    "direction":   direction,
                    "entry_price": entry_price,
                    "exit_price":  exit_price,
                    "pnl":         pnl_dollar,
                    "pnl_pct":     net_pnl_pct * 100,
                    "bars_held":   bars_held,
                    "confidence":  position["confidence"],
                })
                position = None

        # Check for new entry signal
        if position is None and bar["signal"] in ("BUY", "SELL") and bar["cal_conf"] >= threshold:
            entry_price = bar["open_next"] if i + 1 < n else bar["close"]
            size = equity * 0.10   # 10% of equity per trade

            position = {
                "entry_price": entry_price,
                "entry_date":  bar["date"],
                "entry_bar":   i,
                "direction":   bar["signal"],
                "size":        size,
                "confidence":  bar["cal_conf"],
            }

        equity_curve.append({"date": bar["date"], "equity": equity})

    return _calc_metrics(trades, equity_curve, initial_capital)


def _calc_metrics(trades: list[dict], equity_curve: list[dict], initial_capital: float) -> dict:
    if not trades:
        return {
            "total_return": 0.0,
            "sharpe": 0.0,
            "max_drawdown": 0.0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "total_trades": 0,
            "avg_win_pct": 0.0,
            "avg_loss_pct": 0.0,
            "expectancy": 0.0,
        }

    pnls    = [t["pnl"] for t in trades]
    winners = [t for t in trades if t["pnl"] > 0]
    losers  = [t for t in trades if t["pnl"] <= 0]

    total_return = (equity_curve[-1]["equity"] - initial_capital) / initial_capital * 100

    gross_profit = sum(t["pnl"] for t in winners)
    gross_loss   = abs(sum(t["pnl"] for t in losers))
    profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

    win_rate = len(winners) / len(trades) * 100

    avg_win  = sum(t["pnl_pct"] for t in winners) / len(winners) if winners else 0.0
    avg_loss = sum(t["pnl_pct"] for t in losers)  / len(losers)  if losers  else 0.0
    expectancy = (win_rate / 100 * avg_win) + ((1 - win_rate / 100) * avg_loss)

    # Sharpe from equity curve
    eq_vals   = [e["equity"] for e in equity_curve]
    eq_arr    = np.array(eq_vals)
    daily_ret = np.diff(eq_arr) / eq_arr[:-1]
    sharpe    = (np.mean(daily_ret) / np.std(daily_ret) * np.sqrt(252)
                 if np.std(daily_ret) > 0 else 0.0)

    # Max drawdown
    peak  = initial_capital
    max_dd = 0.0
    for e in equity_curve:
        peak   = max(peak, e["equity"])
        dd     = (peak - e["equity"]) / peak
        max_dd = max(max_dd, dd)

    return {
        "total_return":   round(total_return, 2),
        "sharpe":         round(sharpe, 3),
        "max_drawdown":   round(max_dd * 100, 2),
        "win_rate":       round(win_rate, 1),
        "profit_factor":  round(profit_factor, 3),
        "total_trades":   len(trades),
        "winning_trades": len(winners),
        "losing_trades":  len(losers),
        "avg_win_pct":    round(avg_win, 3),
        "avg_loss_pct":   round(avg_loss, 3),
        "expectancy":     round(expectancy, 3),
        "gross_profit":   round(gross_profit, 2),
        "gross_loss":     round(gross_loss, 2),
    }


# ── Signal accuracy ───────────────────────────────────────────────────────────

def compute_signal_accuracy(bars: list[dict], threshold: float, n_forward: int = 5) -> dict:
    """Measure how often ML directional signals were correct based on forward returns."""
    correct = 0
    total   = 0
    conf_correct = []
    conf_wrong   = []

    for i, bar in enumerate(bars):
        if bar["signal"] == "HOLD" or bar["cal_conf"] < threshold:
            continue
        if i + n_forward >= len(bars):
            continue

        entry = bar["close"]
        exit_p = bars[i + n_forward]["close"]
        fwd_ret = (exit_p - entry) / entry

        predicted_up   = bar["signal"] == "BUY"
        actually_up    = fwd_ret > 0

        if predicted_up == actually_up:
            correct += 1
            conf_correct.append(bar["cal_conf"])
        else:
            conf_wrong.append(bar["cal_conf"])
        total += 1

    return {
        "signal_accuracy":    round(correct / total * 100, 1) if total > 0 else 0.0,
        "signals_evaluated":  total,
        "avg_conf_correct":   round(float(np.mean(conf_correct)), 3) if conf_correct else 0.0,
        "avg_conf_wrong":     round(float(np.mean(conf_wrong)), 3)   if conf_wrong   else 0.0,
    }


# ── Main ──────────────────────────────────────────────────────────────────────

async def main() -> None:
    parser = argparse.ArgumentParser(description="ML Model Backtest")
    parser.add_argument("--symbol",    default="",    help="Single symbol (default: all watchlist)")
    parser.add_argument("--days",      type=int, default=365, help="Lookback days (default: 365)")
    parser.add_argument("--threshold", type=float, default=0.55, help="Confidence threshold (default: 0.55)")
    parser.add_argument("--capital",   type=float, default=100_000.0, help="Initial capital (default: 100000)")
    args = parser.parse_args()

    symbols = [args.symbol] if args.symbol else WATCHLIST
    end     = date.today()
    start   = end - timedelta(days=args.days + 100)   # extra bars for warmup

    print("=" * 70)
    print(f"  ML Model Backtest")
    print(f"  Models: {MODEL_DIR}")
    print(f"  Period: {start} → {end}  ({args.days} trading days)")
    print(f"  Confidence threshold: {args.threshold}")
    print(f"  Symbols: {', '.join(symbols)}")
    print("=" * 70)

    print("\nLoading models...")
    meta_model, regime_det, calibration = load_models()
    print(f"  Meta-model: loaded  | {len(meta_model._feature_names)} features")
    print(f"  Regime detector: {'fitted' if regime_det._fitted else 'rule-based fallback'}")
    print(f"  Calibration: {'fitted' if calibration._fitted else 'identity'}")

    all_trades_agg: list[dict] = []
    all_eq_curves:  list[dict] = []
    symbol_results: list[dict] = []

    for sym in symbols:
        print(f"\n{'─' * 60}")
        print(f"  {sym}")
        df = _fetch_yf(sym, start, end)
        if df is None or len(df) < 60:
            print(f"  SKIP: insufficient data ({len(df) if df is not None else 0} bars)")
            continue

        # Trim to requested days
        df = df.iloc[-args.days - 50:]  # +50 for feature warmup

        print(f"  Data: {len(df)} bars  |  {df.index[0].date()} → {df.index[-1].date()}")

        bars = build_features_for_symbol(df, sym, regime_det, meta_model, calibration)
        if not bars:
            print(f"  SKIP: feature pipeline returned no bars")
            continue

        # Tag bars with symbol for trade tracking
        for b in bars:
            b["symbol"] = sym

        acc  = compute_signal_accuracy(bars, args.threshold)
        perf = simulate_trades(bars, args.threshold, args.capital)

        buy_sigs  = sum(1 for b in bars if b["signal"] == "BUY"  and b["cal_conf"] >= args.threshold)
        sell_sigs = sum(1 for b in bars if b["signal"] == "SELL" and b["cal_conf"] >= args.threshold)
        hold_sigs = sum(1 for b in bars if b["signal"] == "HOLD" or b["cal_conf"]  < args.threshold)

        print(f"  Signals: BUY={buy_sigs}  SELL={sell_sigs}  HOLD/filtered={hold_sigs}")
        print(f"  Accuracy (directional): {acc['signal_accuracy']:.1f}%  ({acc['signals_evaluated']} signals)")
        print(f"  Return: {perf['total_return']:+.2f}%  |  Sharpe: {perf['sharpe']:.3f}  |  MaxDD: {perf['max_drawdown']:.2f}%")
        print(f"  Trades: {perf['total_trades']}  |  Win%: {perf['win_rate']:.1f}%  |  PF: {perf['profit_factor']:.3f}")

        symbol_results.append({
            "symbol":        sym,
            "bars":          len(bars),
            "buy_signals":   buy_sigs,
            "sell_signals":  sell_sigs,
            **acc,
            **perf,
        })

    # ── Aggregate summary ──────────────────────────────────────────────────────
    if not symbol_results:
        print("\nNo results.")
        return

    print(f"\n{'=' * 70}")
    print(f"  AGGREGATE SUMMARY  ({len(symbol_results)} symbols)")
    print(f"{'=' * 70}")
    print(f"\n{'Symbol':<12} {'Ret%':>8} {'Sharpe':>8} {'MaxDD%':>8} {'WinRate':>8} {'Trades':>7} {'Acc%':>7}")
    print("-" * 65)

    for r in symbol_results:
        print(
            f"{r['symbol']:<12} {r['total_return']:>+8.2f} {r['sharpe']:>8.3f} "
            f"{r['max_drawdown']:>8.2f} {r['win_rate']:>8.1f}% {r['total_trades']:>7} "
            f"{r['signal_accuracy']:>6.1f}%"
        )

    avg_return    = np.mean([r["total_return"]    for r in symbol_results])
    avg_sharpe    = np.mean([r["sharpe"]          for r in symbol_results])
    avg_winrate   = np.mean([r["win_rate"]        for r in symbol_results])
    avg_drawdown  = np.mean([r["max_drawdown"]    for r in symbol_results])
    avg_accuracy  = np.mean([r["signal_accuracy"] for r in symbol_results])
    total_trades  = sum(r["total_trades"] for r in symbol_results)

    print("-" * 65)
    print(f"{'AVERAGE':<12} {avg_return:>+8.2f} {avg_sharpe:>8.3f} {avg_drawdown:>8.2f} "
          f"{avg_winrate:>8.1f}% {total_trades:>7} {avg_accuracy:>6.1f}%")
    print()
    print(f"  Directional accuracy:  {avg_accuracy:.1f}%  (vs 33.3% random 3-class baseline)")
    print(f"  Average Sharpe ratio:  {avg_sharpe:.3f}")
    print(f"  Average return:        {avg_return:+.2f}%")
    print(f"  Average max drawdown:  {avg_drawdown:.2f}%")
    print(f"  Total simulated trades:{total_trades}")
    print()


if __name__ == "__main__":
    asyncio.run(main())
